language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install
services:
- postgresql
before_script:
- psql -c 'create database express_javascript;' -U postgres
- psql -c "CREATE USER root WITH PASSWORD null;" -U postgres
- npm run build
- npm install -g sequelize-cli
- sequelize db:migrate
script:
- npm run test
after_success:
- npm run generate-lcov
- npm run coveralls-coverage
deploy:
  provider: heroku
  api_key:
    secure: FsQvXW5Pxnjtoo8aGXzeVvr2PYsxEPVh4DbrqdwO1/eC/YEN3fkJU9bUZdnDPj60LwzMV+/zszBrzDYGi4x43cqCrRMPzwV3tQzpyO8HXES8a70GNt/buMZ6ldl2qb8+qILZpnzF3InuwkDR8TAiL1fbQDmBCRZ0OMoZ69Oinnx4z2V3MX3pzwBQ7VzSsl6QHa5KbXsQTW6R8w6ErHjbq0BGMNaXOaoadtyyEpzHobPXDz0UMBZ9lgAVfjz6H9MOLTQQoYxPZ/OPmco3cO38ehb9P3ox5L0M7iYUg5zh9mrID/stRu1J9RyX93tKYoKGEWm38aT6zJ48AVUPIMoeBLeF43DaAVPgQn4qXHKBGWt1MiVTWnz5wksoPc2+8wxgvQatmunUDHWzAHwXoQ2YMVFu9DIYr05dM8nn8jhhcMRXbTj2N1tCkuqPnK4NUnMg7AQS9PY2sexrusLGvnaSRdojE58ijk8BB9CZOuj2/AL2P2suQKA3VyvwbVWh/IEVzSrxm3h7bWJ8BlqV36oORdZzCMnD4rVlJ38DLR6dFh3bQ9P3icDTYo0EQ1oG0XUTXC5wjv5SlxVt7oSaLqCW7PPDXmJxXEGB2WmeiB1qyKshu+Sm+lravKMyDATMjgu92KbHFsX4yjHlaFCjorTtJtGUqRCys9waGtUq1L8Nx8A=
  app: "nodejs-express-postgre-sequliz"
  on:
    repo: vaughan189/nodejs-express-postgresql-sequelize-template
  skip_cleanup: true
